services:
  - type: web
    name: hms-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.app:app"
    plan: free
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: yourpassword
      - key: DB_NAME
        value: HMS

